# External Secret for Pathfinder
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pathfinder-external-secret
  namespace: starknet-node
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store  # Change to your preferred store
    kind: SecretStore
  target:
    name: pathfinder-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        PATHFINDER_ETHEREUM_API_URL: "{{ .pathfinder_ethereum_api_url }}"
        RUST_LOG: "{{ .rust_log | default \"info\" }}"
  data:
  - secretKey: pathfinder_ethereum_api_url
    remoteRef:
      key: starknet/pathfinder
      property: ethereum_api_url
  - secretKey: rust_log
    remoteRef:
      key: starknet/pathfinder
      property: rust_log
---
# External Secret for Validator A
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: validator-a-external-secret
  namespace: starknet-node
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store  # Change to your preferred store
    kind: SecretStore
  target:
    name: validator-a-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        REMOTE_SIGNER_URL: "{{ .remote_signer_url }}"
        OPERATIONAL_PRIVATE_KEY: "{{ .operational_private_key }}"
        RUST_LOG: "{{ .rust_log | default \"info\" }}"
  data:
  - secretKey: remote_signer_url
    remoteRef:
      key: starknet/validator-a
      property: remote_signer_url
  - secretKey: operational_private_key
    remoteRef:
      key: starknet/validator-a
      property: operational_private_key
  - secretKey: rust_log
    remoteRef:
      key: starknet/validator-a
      property: rust_log
---
# External Secret for Validator B
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: validator-b-external-secret
  namespace: starknet-node
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store  # Change to your preferred store
    kind: SecretStore
  target:
    name: validator-b-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        REMOTE_SIGNER_URL: "{{ .remote_signer_url }}"
        OPERATIONAL_PRIVATE_KEY: "{{ .operational_private_key }}"
        RUST_LOG: "{{ .rust_log | default \"info\" }}"
  data:
  - secretKey: remote_signer_url
    remoteRef:
      key: starknet/validator-b
      property: remote_signer_url
  - secretKey: operational_private_key
    remoteRef:
      key: starknet/validator-b
      property: operational_private_key
  - secretKey: rust_log
    remoteRef:
      key: starknet/validator-b
      property: rust_log
---
# RBAC for External Secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: starknet-node
  name: external-secrets-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["external-secrets.io"]
  resources: ["externalsecrets", "secretstores"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-rolebinding
  namespace: starknet-node
subjects:
- kind: ServiceAccount
  name: external-secrets-sa
  namespace: starknet-node
roleRef:
  kind: Role
  name: external-secrets-role
  apiGroup: rbac.authorization.k8s.io