apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-secrets
  namespace: external-secrets-system
spec:
  chart: external-secrets
  repo: https://charts.external-secrets.io
  targetNamespace: external-secrets-system
  valuesContent: |-
    installCRDs: true
    webhook:
      port: 9443
    certController:
      enabled: true
---
# Alternative: Manual CRD installation if Helm is not available
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-secrets-install-info
  namespace: external-secrets-system
data:
  install-commands: |
    # If the HelmChart above doesn't work, run these commands manually:
    # helm repo add external-secrets https://charts.external-secrets.io
    # helm install external-secrets external-secrets/external-secrets -n external-secrets-system --create-namespace --wait
    
    # Or using kubectl:
    # kubectl apply -f https://raw.githubusercontent.com/external-secrets/external-secrets/main/deploy/crds/bundle.yaml
    # kubectl apply -f https://raw.githubusercontent.com/external-secrets/external-secrets/main/deploy/charts/external-secrets/templates/rbac.yaml
    # kubectl apply -f https://raw.githubusercontent.com/external-secrets/external-secrets/main/deploy/charts/external-secrets/templates/deployment.yaml