apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-suffix-validator
  labels:
    app: grafana-suffix-validator
    grafana-tier: client
    validator: suffix-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-suffix-validator
  template:
    metadata:
      labels:
        app: grafana-suffix-validator
        grafana-tier: client
        validator: suffix-validator
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "suffix-validator-pass123"
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Viewer"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
          readOnly: true
        - name: grafana-dashboards-config
          mountPath: /etc/grafana/provisioning/dashboards
          readOnly: true
        - name: grafana-validator-dashboards
          mountPath: /var/lib/grafana/dashboards
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-suffix-validator-pvc
      - name: grafana-datasources
        configMap:
          name: grafana-suffix-validator-datasources
      - name: grafana-dashboards-config
        configMap:
          name: grafana-dashboards-config
      - name: grafana-validator-dashboards
        configMap:
          name: grafana-suffix-validator-dashboards
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-ethchi-validator
  labels:
    app: grafana-ethchi-validator
    grafana-tier: client
    validator: ethchi-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-ethchi-validator
  template:
    metadata:
      labels:
        app: grafana-ethchi-validator
        grafana-tier: client
        validator: ethchi-validator
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "ethchi-validator-pass123"
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Viewer"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
          readOnly: true
        - name: grafana-dashboards-config
          mountPath: /etc/grafana/provisioning/dashboards
          readOnly: true
        - name: grafana-validator-dashboards
          mountPath: /var/lib/grafana/dashboards
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-ethchi-validator-pvc
      - name: grafana-datasources
        configMap:
          name: grafana-ethchi-validator-datasources
      - name: grafana-dashboards-config
        configMap:
          name: grafana-dashboards-config
      - name: grafana-validator-dashboards
        configMap:
          name: grafana-ethchi-validator-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-suffix-validator-service
  labels:
    app: grafana-suffix-validator
    grafana-tier: client
    validator: suffix-validator
spec:
  selector:
    app: grafana-suffix-validator
  ports:
  - port: 3001
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-ethchi-validator-service
  labels:
    app: grafana-ethchi-validator
    grafana-tier: client
    validator: ethchi-validator
spec:
  selector:
    app: grafana-ethchi-validator
  ports:
  - port: 3002
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-suffix-validator-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-ethchi-validator-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi