apiVersion: apps/v1
kind: Deployment
metadata:
  name: pathfinder
  labels:
    app: pathfinder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pathfinder
  template:
    metadata:
      labels:
        app: pathfinder
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9545"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: pathfinder
        image: eqlabs/pathfinder:latest
        ports:
        - containerPort: 9545
          name: http-rpc
        - containerPort: 9546
          name: metrics
        env:
        - name: RUST_LOG
          value: "info"
        - name: RPC_ROOT_VERSION
          value: "v08"
        args:
        - "--ethereum.url"
        - "$(PATHFINDER_ETHEREUM_API_URL)"
        - "--data-directory"
        - "/usr/share/pathfinder/data"
        - "--http-rpc"
        - "0.0.0.0:9545"
        - "--rpc.cors-domains"
        - "*"
        - "--rpc.websocket.enabled"
        envFrom:
        - secretRef:
            name: pathfinder-secrets
        resources:
          requests:
            memory: "8Gi"
            cpu: "4000m"
          limits:
            memory: "12Gi"
            cpu: "6000m"
        volumeMounts:
        - name: pathfinder-data
          mountPath: /usr/share/pathfinder/data
      volumes:
      - name: pathfinder-data
        persistentVolumeClaim:
          claimName: pathfinder-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pathfinder-service
  labels:
    app: pathfinder
spec:
  selector:
    app: pathfinder
  ports:
  - name: http-rpc
    port: 9545
    targetPort: 9545
  - name: metrics
    port: 9546
    targetPort: 9546
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pathfinder-pvc
  labels:
    app: pathfinder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 300Gi
