# AWS Secrets Manager SecretStore
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-store
  namespace: starknet-node
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2  # Update to your region
      auth:
        secretRef:
          accessKeyID:
            name: aws-credentials
            key: access-key-id
          secretAccessKey:
            name: aws-credentials
            key: secret-access-key
---
# Google Secret Manager SecretStore
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secrets-store
  namespace: starknet-node
spec:
  provider:
    gcpsm:
      projectId: your-gcp-project-id
      auth:
        workloadIdentity:
          clusterLocation: us-central1  # Update to your cluster location
          clusterName: your-cluster-name
          serviceAccountRef:
            name: external-secrets-sa
---
# Azure Key Vault SecretStore
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-secrets-store
  namespace: starknet-node
spec:
  provider:
    azurekv:
      vaultUrl: https://your-keyvault.vault.azure.net/
      authType: WorkloadIdentity
      serviceAccountRef:
        name: external-secrets-sa
---
# HashiCorp Vault SecretStore
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secrets-store
  namespace: starknet-node
spec:
  provider:
    vault:
      server: https://vault.example.com:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
          serviceAccountRef:
            name: external-secrets-sa
---
# Kubernetes Secret Store (for development/testing)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-secrets-store
  namespace: starknet-node
spec:
  provider:
    kubernetes:
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets-sa
---
# Service Account for External Secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: starknet-node
  annotations:
    # For AWS IAM Role
    eks.amazonaws.com/role-arn: arn:aws:iam::YOUR_ACCOUNT:role/external-secrets-role
    # For GCP Workload Identity
    iam.gke.io/gcp-service-account: external-secrets@your-project.iam.gserviceaccount.com
    # For Azure Workload Identity
    azure.workload.identity/client-id: your-client-id